#include "pwm_generate.h"
void vTim2_DisablePWM(void){
  TIM2->CR1&=~TIM2_CR1_CEN;
  TIM2->CCER1&=~TIM2_CCER1_CC2E;/*ENABLE CAPTURE/COMPARE FOR CHANNEL 2 AND 3*/
  TIM2->CCER2&=~TIM2_CCER2_CC3E;/*ENABLE CAPTURE/COMPARE FOR CHANNEL 2 AND 3*/
}
void vTim2_EnablePWM(void){
  TIM2->CR1|=TIM2_CR1_CEN;
  TIM2->CCER1|=TIM2_CCER1_CC2E;/*ENABLE CAPTURE/COMPARE FOR CHANNEL 2 AND 3*/
  TIM2->CCER2|=TIM2_CCER2_CC3E;/*ENABLE CAPTURE/COMPARE FOR CHANNEL 2 AND 3*/
}

